### ISSUE TITLE
octoprint V1.9 Windows 10 install error

### ISSUE THREAD

**Issue by Grizzord** [cmuche/octoprint-timelapseplus#125]
i am trying to install this and am getting the "install: unknown" in the popup box.

I am currently using Python 3.10.11
Pip 22.0.1

I understand that in the past the pip version could cause issues with installing certain plugins. what version of pip should I be using
log is also attached.
any help would be appreciated Thank you. 
[plugin_pluginmanager_console (6).log](https://github.com/cmuche/octoprint-timelapseplus/files/11855818/plugin_pluginmanager_console.6.log)

**Comment by Grizzord** [comment]
[octoprint.log](https://github.com/cmuche/octoprint-timelapseplus/files/11855835/octoprint.log)
found that the bottom of this log actually mentions the loading error being that PIL is not found still not sure how to correct this

**Comment by cmuche** [comment]
Hi @Grizzord 

That's weird. Timelapse+ uses Pillow which is (as you can see [here](https://pillow.readthedocs.io/en/stable/installation.html)) not working when PIL is installed simultaneously. Please check if PIL is installed on your system.

**Comment by Grizzord** [comment]
so i suppose we can close this. long story short, the windows machine i was using decided to implode and not boot anymore. i ended up installing linux on it and e erything just works on linux so ill jsut stick with that. not sure what was going on with the windows install but it seems every plugin on windows needs different versions of python, pip, and pil. its very frustrating. hopefully windows is as seemless as linux someday for octoprint
