### ISSUE TITLE
Part: "add timecode: Analog Clock" to start at 12:00.

### ISSUE THREAD

**Issue by Foxies-CSTL** [cmuche/octoprint-timelapseplus#130]
Hi,
Thank you for your plugin and I'm trying to configure it to have a analog clock on my prints. It works fine but the clock display never starts at 12:00 and the start seems to depend on the current time.
Would it be possible to have an option to check that the clock starts at 12:00 and thus have a better overview of the printing time.
Thank you for your superb work.

**Comment by cmuche** [comment]
Hi @Foxies-CSTL 
Starting the clock at 12 would lead to a wrong time of the day, which is the general idea of the analog clock option. But you can choose one of the _Print Time_ optons which display the _elapsed_ time in the timelapse. I hope this helps.

**Comment by Foxies-CSTL** [comment]
Yes, I understand but it was to have a chronometer like visual in sports.

Thanks
