### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by fly74** [cmuche/octoprint-timelapseplus#131]
Since multicam has started with OP 1.9.2 and Mulicam plugin, it would be nice to snap more cams at a time and render them together maybe side by side or one up and the other down. If you know what I mean?

**Comment by cmuche** [comment]
Hi @fly74 
Sorry for my late reply. 
Yes - this _would_ be possible. But it would also need a lot of work since the whole capturing system needs to be touched. I'll keep it in the backlog, maybe for a later version.
