### ISSUE TITLE
Option to Render on different pc

### ISSUE THREAD

**Issue by Blendan1** [cmuche/octoprint-timelapseplus#140]
It would be nice to be able to render the timelaps on a driffrent pc.

my issue is that rendering the timelapse is very slow and also fails a lot of times on my pi zero 2, so it would be nice to be able to just export the frames (with settings if posible) and then run the render job on a drffrent pc via cli/script

**Comment by cmuche** [comment]
Hi @Blendan1 
You can always download your frame collections and upload them to another, more powerful host running OctoPrint to render them there. A syncing or CLI feature is not intended at this point.
