### ISSUE TITLE
Cound not find or run FFMpeg

### ISSUE THREAD

**Issue by seanmcne** [cmuche/octoprint-timelapseplus#29]
Hi, I just installed this plugin via the ocotprint plugin installer and I get this error message - should it download it's own update of FFMpeg or be able to discover the existing path?  If not, do you have any installation instructions for the plugin?  Thx!

**Comment by cmuche** [comment]
Hey there!
FFmpeg needs to be installed on your system and there is an option at the settings page where you have to set the executable path manually. See this screenshot: https://github.com/cmuche/octoprint-timelapseplus/raw/master/assets/screenshots/settings-general.png

Please let me know if this fixes the problem for you!

**Comment by seanmcne** [comment]
Hi thanks for the update - do you have instructions on how to do this when it's installed in a Pi? I wasn't sure if this is something I should just know how to do or if there's a reference for the steps to install it. Thx!

**Comment by cmuche** [comment]
That depends on your system ;-) 
If it's not installed yet you can install it e.g. via a packet manager like apt: `sudo apt install ffmpeg`.
To find out where the executable is located you can then use `which ffmpeg`. If you have a distribution like OctoPi i don't know if FFmpeg is maybe even preinstalled. In this case you can also test it by running `ffmpeg -version`.

**Comment by andremariz** [comment]
I have set the path and im still having the same error.....

**Comment by cmuche** [comment]
Is the built-in timelapse plugin able to render videos with the same FFmpeg path?
Timelapse+ throws this error if just a `ffmpeg -version` is not successful:

`        try:
            cmd = [ffmpegPath, '-version']
            result = subprocess.run(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE, universal_newlines=False)
        except:
            raise Exception('Could not find or run FFmpeg')
`

Maybe OctoPrint has no rights to execute FFmpeg on your system? Could you maybe try to execute `ffmpeg -version` manually on your system?

**Comment by cmuche** [comment]
Hi @seanmcne 
Is the problem still there or were you able so solve it?
Would appreciate a quick update 😃

**Comment by seanmcne** [comment]
> Hi @seanmcne @andremariz Is the problem still there or were you able so solve it? Would appreciate a quick update 😃

Apologies for the delay - no, it doesn't appear to be installed on my raspberry pi (maybe it is but it isn't clear where it is🤷).  I was looking to quickly download and use the package and figured it would download what was needed.  If it's possible, it would be great if there was a way to discover/find ffmpeg if it existed or an option to have the package include it as part of the download (I'm not sure if it's like nuget where you could define a dependency?).  I'll eventually come back to this when I have to do another batch of printing.  Thanks for your very quick response and work on the plugin, I look forward to hopefully get it working sometime in the future!

**Comment by cmuche** [comment]
Hi @seanmcne 
If FFmpeg is installed (assuming you're on Windows and it's in your PATH) you can use `where ffmpeg`, on linux `which fmpeg` to find the path to the executable. Then that's what you enter in the Timelapse+ settings. It would be possible to do that in Timelapse+, maybe that could be a feature for the future. Unfortunately I can't bundle FFmpeg since it has a different license which doesn't allow it with the plugin license.

**Comment by seanmcne** [comment]
I'm not using windows - I run octoprint on a raspberry pi.

**Comment by cmuche** [comment]
Okay, then the second command should work. I would be happy to know if it worked.
