### ISSUE TITLE
Playback Issues / Webcam Snapshot URL ?

### ISSUE THREAD

**Issue by Rebel154** [cmuche/octoprint-timelapseplus#36]
I'm trying to get this plug in working, but with the lack of installation and settings instructions, it's a bit difficult. I have managed to figure out most of it, but I am struggling with the Webcam Snapshot URL, as the text box in your screenshot is too short to show the full URL (assuming there is more after '/webcam') I've tried to guess what it should be without much success.

What is the correct entry for the Webcam Snapshot URL please?

**Comment by Rebel154** [comment]
Thanks for the quick reply. I have corrected the Webcam Snapshot URL to be the same as the Octoprint standard plugin entry as per your image above. 

This is my standard setting for the Octoprint built-in plugin. Should Timelapse support be enabled on this screen (I see yours isn't)? The Test buttons on here are successful.

![2023-04-28 (11)](https://user-images.githubusercontent.com/30339064/235167062-ce200b89-348b-42f9-8fa7-dd223c579a8c.png)

This is my settings in Timelapse+. All settings below this are as per your screenshots in the Readme.md

![2023-04-28 (4)](https://user-images.githubusercontent.com/30339064/235167240-7f065d76-4f8b-4e65-9f5d-fc1c919da65e.png)

This is what I am seeing whilst the print is ongoing/completed. 

![2023-04-28 (10)](https://user-images.githubusercontent.com/30339064/235167586-bff6d7f3-c500-4eea-ba16-8ae161d1d964.png)

I'm using a Raspberry Pi 4 with the OctoPi 1.0.0 installed with Octoprint 1.8.7 and Python 3.9.2.

**Comment by cmuche** [comment]
You're welcome! :-)
Since I released the plugin just some days ago I would appreciate you feedback (just if it works now or not).

**Comment by Rebel154** [comment]
@cmuche, OK, I now have the plugin working, but there are a couple of issues with my system.

1. There doesn't appear to be a suitable video player installed on the Raspberry Pi (latest Bullseye Lite version) that will play the Timelapse previews. I tried installing VLC for Raspberry Pi, but that did not help (even after a reboot). This is the screen I get when trying to play a Timelapse video:

![2023-04-28 (12)](https://user-images.githubusercontent.com/30339064/235212687-0b750b60-fb8f-4187-8964-fbdbf5e52970.png)

2. My Windows 11 Pro PC will not play the videos using the default Media Player, nor with the legacy Windows Media Player. They will play with VLC. This is the pop-up message from Media Player:

![2023-04-28 (13)](https://user-images.githubusercontent.com/30339064/235213079-162c7fd6-5036-49e6-983b-35bcda335cba.png)

3. After either rendering a video or downloading one to my PC (I'm not sure which), I randomly get the 'Please Reload...' pop-up. I can't reproduce it on demand, unfortunately.

Other than that, it seems to run OK.

**Comment by cmuche** [comment]
That's weird. Can you maybe tell me what FFmpeg version you are using and which encoders are available? You can find out your version by running `ffmpeg -version` and `ffmpeg -encoders` manually on your host machine. Currently I'm using the default codec for FFmpeg, maybe you have a different or older version which doesn't support H264.

Maybe you could also attach your video file here? Or attach the codec information from VLC (via `CTRL+i`) like this:
![image](https://user-images.githubusercontent.com/14235338/235271773-05f30531-12c3-48f3-a1e3-cea666383d15.png)

It could also be a good idea to hardcode H264 or checking the installed encoders first or making it configurable via the settings. Can you play the videos rendered by the stock timelapse plugin without problems in your browser?

**Comment by Rebel154** [comment]
Morning, I've attached a zip file with my video from TimeLapse+ as well as a text file with the output from the 2 ffmpeg commands and the VLC codec info from my PC.  The video is only 2 seconds long, as it was only a 65-layer print I used for testing purposes.

If I drag and drop the video onto my browser (Firefox v112.0.2), I get a 'video file is corrupt' message. It will play if I drag & drop into Chrome (which I rarely use unless I have to). Similarly, it runs in MS Edge too. Strange.

[FFMPEG Raspberry Pi (Rebel154).zip](https://github.com/cmuche/octoprint-timelapseplus/files/11358667/FFMPEG.Raspberry.Pi.Rebel154.zip)

Thanks for your reply, once more.

**Comment by cmuche** [comment]
Hey @Rebel154 !

Wow - thank you for your effort and help - I appreciate that very much!

I did some testing and research with your provided files and Firefox v112.0.2. First of all your video file looks good regarding the codec information. You even have a newer FFmpeg version than me. So I turned on the browser topic and installed Firefox since I developed and tested with Chrome. And you're right: There is a difference between these browsers. I was also not able to play any rendered video (including yours) and also the stock timelapse videos won't play as well. Strangely the FF is not able to play H264 videos on its own. Since it depends on the codecs locally installed, maybe a workaround would be to install the H264 codecs on your machine, buw I haven't tested that yet. But I found out that WEBM are working with FF and for testing I let Timelapse+ render in this format. Turns out that FF can play these.

Maybe you can verify on your system with your FF as well?
[3DBenchy SNAP - DRAFT 0.28mm - 3DJAKE ecoPLA 200C_12042023131757_20230429124344.webm](https://user-images.githubusercontent.com/14235338/235298908-549a6e9a-1b7e-4fd8-b08b-f5e5cea5a4a0.webm)

If that's the case (I even had this already in mind) I think it would be good to focus on bringing multiple and configurable output settings for the next update iteration. I'll figure out if there is maybe another option to play H264 videos in FF as well.

Thank you again for your support and information! :-)

**Comment by Rebel154** [comment]
Hi @cmuche, your .webm file plays fine with all options on my PC - Media Player, VLC, Windows Media Player Legacy (which complains about not recognizing the extension, but plays the video anyway), as well as all three browsers on my PC.

Lack of H.264 support in Firefox is a licencing issue. See [this web page](https://support.mozilla.org/en-US/kb/open-h264-plugin-firefox) for more info. I've checked my installation of FF and it has OpenH264 installed and active.

**Comment by cmuche** [comment]
Hey @Rebel154 

Sorry for my late reply, but I just released v1.1.0 which includes the option for multiple video formats and codecs. Your OctoPrint should inform you soon.
In this course I also tried to investigate the FF problems but I wasn't really succesful. Also on my machine FF *should* be able to play H.264 MP4 videos but it just... doesn't and honestly I don't know. I also built an error message if the browser is not able to play a video file but FF doesn't throw an error on those files at all and claims to be able to play them. So in order for you to watch the videos in your browser you could switch to the WebM option. This works well. At least on my machine.

I hope that helps and as always: Don't hesitate to post ideas, comments, bugs, ...
Your help was and will always be highly appreciated! Thank you!

**Comment by Rebel154** [comment]
Hi @cmuche, no worries for the late reply, I imagine it took you a while to do the coding. 

My PC should also be able to play H.264 files via FF, as the OpenH264 plugin is installed and active. No idea what's going on there.

I re-rendered one of my Frame Collections as a webm (HQ V9) file, and that plays OK in the Timelapse+ plugin preview mode. It also plays fine in everything except the Windows 11 Media Player - which is strange because the webm test file you sent me plays OK in that application.  Edit: Just checked, your file is V8 whereas my file is V9, I'll have another go with V8.

I'll try a new video next time I have my printers running.

Thanks for the update.

**Comment by cmuche** [comment]
Hey @Rebel154 
Maybe in the future there will be a fix (?) for FF... ;-) Still don't know what's going on there.
But I'm happy to hear that whe WebM files work for you 👍 Codecs can cause headaches sometimes.
Again thank you very very very much for your help and input! It really helped me very much and I highly appreciate your effort!

**Comment by cmuche** [comment]
Hey @Rebel154 it's me again...
I just wanted to let you know that the MP4 issue in Firefox should be solved now. Seems like Firefox doesn't like any pixel formats other than `yuv420p`. The fix is included in the 1.3.0 version. So hope this fixes for playback problem 😃

**Comment by Rebel154** [comment]
Hi Chris, does this plugin work with Octopi v1.9.0 with the new camera stack?  I’ve updated both my printers to run with the latest Octoprint release, but have yet to install your plug-in. 

Thanks for the heads up too.

**Comment by cmuche** [comment]
Hi @Rebel154 
Timelapse+ works with OctoPrint 1.9.0. But it still has its own snapshot URL to configure so it doesn't use the new camera stack.
