### ISSUE TITLE
can only concatenate str (not "int") to str

### ISSUE THREAD

**Issue by djepsylon** [cmuche/octoprint-timelapseplus#38]
hi, i have this message in the timelapse+ plugin windox and every settings are okay can you help me?
"can only concatenate str (not "int") to str"

**Comment by cmuche** [comment]
Hi @djepsylon 
When and where does this error occur? On the main tab or when you are in the settings?
Can you maybe provide the full error and stack trace that is printed out in the OctoPrint log? That would help me very much to understand what happened.

**Comment by cmuche** [comment]
Okay, great that your error is resolved. But can you remember where and where it occured?
Which browser are you using? Firefox has some probems with the video playback, see https://github.com/cmuche/octoprint-timelapseplus/issues/36#issuecomment-1533797615
As I can see you are not yet using the 1.1.0 version which contains multiple video formats (there are no format labels on your videos). Can you maybe install this version and try out e.g. the WebM settings? Can you download and play the videos locally on your system (for example with VLC)?

**Comment by djepsylon** [comment]
hi, tks or your answers.
i ve tried with the last version and localy i can see the videos but inverted lolll
![WM-Screenshots-20230511004245](https://github.com/cmuche/octoprint-timelapseplus/assets/96573654/baf42f68-98b2-4d89-8db8-2e941cf2884f)

**Comment by cmuche** [comment]
Okay, now that is _really_ weird. Did your webcam provide those inverted images? Are they already inverted in the Frame Collection? Could you maybe upload your frame collection here so I can investigate on what's going on there? Thank you in advance!

**Comment by djepsylon** [comment]
hi, here is the frames you want

https://we.tl/t-g8UCMzg6S5

**Comment by cmuche** [comment]
Hi @djepsylon 
Thanks for your reply. Could you maybe provide the raw Frame Collection (you can download them now in v1.2.0):
![image](https://github.com/cmuche/octoprint-timelapseplus/assets/14235338/a53e9527-7aff-4aa5-a069-b9c0cabce99d)

Is it correct when rendering a timelapse via the stock timelapse functionality? But as I can see it is not really inverted. Looks like it's a wrong color format or color channel problem...

**Comment by djepsylon** [comment]
hi, i give you the file you want and i ve do your 1.2.2 update and change my video format and it is upsidedown too loll
![WM-Screenshots-20230521071418](https://github.com/cmuche/octoprint-timelapseplus/assets/96573654/2170109e-8d37-4203-b716-ae70df5a4d2c)
https://we.tl/t-UKjtt37Wjq

**Comment by cmuche** [comment]
Hi @djepsylon 
Unfortunately you uploaded a final video again. I'd need the raw Frame Collection to investigate...

**Comment by djepsylon** [comment]
> Hi @djepsylon Unfortunately you uploaded a final video again. I'd need the raw Frame Collection to investigate...

@cmuche  i upload on this button like you see ans like you do on your picture
![WM-Screenshots-20230521211632](https://github.com/cmuche/octoprint-timelapseplus/assets/96573654/a4550bee-eb7e-4592-90da-21d01f090147)

**Comment by cmuche** [comment]
You can also download a Frame Collection directly in v1.2.0 and above, see my answer: https://github.com/cmuche/octoprint-timelapseplus/issues/38#issuecomment-1546663166

**Comment by djepsylon** [comment]
https://we.tl/t-23DuTB4FoR
is this? @cmuche

**Comment by cmuche** [comment]
Okay, the images in the Frame Collection are already strange. Can you confirm that your webcam delivers the correct images? E.g. in the Controls tab?

**Comment by djepsylon** [comment]
hi,
i confirm
![WM-Screenshots-20230526031104](https://github.com/cmuche/octoprint-timelapseplus/assets/96573654/e5a6ef27-587c-43fd-9ebb-163d91410f7e)

**Comment by cmuche** [comment]
Thanks for your answer. But is confirms that the camera does __not__ return a correct image if it's even wrong in pthe camera preview...?! If that's the image your camera delivers, it seems not be an issue with Timelapse+.

**Comment by djepsylon** [comment]
hum in the screen in the control pannel the camera is in he good way i think you are wrong or i don't undurstand. i re post a picture of my camera in control panel with bette
![WM-Screenshots-20230527032710](https://github.com/cmuche/octoprint-timelapseplus/assets/96573654/6586c437-a030-46aa-b6aa-61027a989dda)
r vision here

**Comment by cmuche** [comment]
Ah okay, you mean the rotation now? I thought you meant that the image seems inverted. Couldn't really make out that the image is rotated in your example.

Does the "Test paths and camera" button in the setting menu already show the wrong image? Maybe a flip/rotate option for camera preprocessing would be helpful as a future feature then.
