### ISSUE TITLE
'test paths and webcam settings' does not use the current ffprobe path

### ISSUE THREAD

**Issue by Harryhar** [cmuche/octoprint-timelapseplus#65]
The plugin can find the ffmpeg, but keeps complaining about the ffprobe. Tripple checked the path, but it keep nagging about not being able to find the ffprobe.

ffmpeg path = /usr/bin/ffmpeg
ffprobe path = /usr/bin/ffprobe

If I run the command for ffprobe in a terminal it responds correct en shows me te used libraries etc.

**Comment by cmuche** [comment]
Hi @Harryhar 
Is there maybe a space at the start or end of your FFprobe path?
What does the error message tell you exactly?

![image](https://github.com/cmuche/octoprint-timelapseplus/assets/14235338/00a87a1f-c9df-4e0f-be4b-e9ac21693091)

**Comment by Harryhar** [comment]
There is no speca before or after the command.

This is the error shown by the plugin :
![image](https://github.com/cmuche/octoprint-timelapseplus/assets/282404/5960bc57-1c9d-4e15-a16f-f5ef7557ca0a)

**Comment by Harryhar** [comment]
Found the bug.

The Test button in the config panel uses the stored information. It should use the just entered information.

After saving the settings and going back to the Timelapse+ settings, the test button works as expected.

**Comment by Harryhar** [comment]
I am using the latest version, and I am using Chrome.

The problem is with the ffprobe conmand, the ffmpeg command works like expected.

**Comment by cmuche** [comment]
Hi @Harryhar 
Yes - you are right! Only the FFprobe command doesn't work properly. Sorry for that.
I'll take this as a bug and will fix it soon.
Thank you for your input! 👍

**Comment by Harryhar** [comment]
Glad to be of help.

**Comment by cmuche** [comment]
Released with v1.2.2. 👍
