### ISSUE TITLE
Need help with Capture Command

### ISSUE THREAD

**Issue by P0tth34d** [cmuche/octoprint-timelapseplus#79]
Hi there, 
First of all thank you very much for that new Timelapse Plugin.
I was looking for a solution to remove the background out of my Videos for a long time because the Printer and the camera captures my wife at her desk is she is working from home.

It is a bit embarrassing but I cannot get the plugin taking Snapshots from snapshot Command.
It works fine if i use the capture mode "Timer"
But if I use Command and leave it as it is with "SNAPSHOT" it does not capture anything.
I also tried "@ Snapshot" and "Snapshot" and  "@ SNAPSHOT" (without the blank but if i do not add a blank here it tags a User called Snapshot :-) )
I use CURA as Slicer and also tried Prusa Slicer because of the "At Layer Change" is a bit more comfortable

Timelapse+ Settings: 
![image](https://github.com/cmuche/octoprint-timelapseplus/assets/132906654/3b581d7e-667e-46e7-adf9-cf69272ba7ed)

Gcode Example:
![image](https://github.com/cmuche/octoprint-timelapseplus/assets/132906654/9c5ba881-eabd-4ecc-ba34-eb1b9b39394b)

Outcome:
![image](https://github.com/cmuche/octoprint-timelapseplus/assets/132906654/880b3b3d-bfae-4a84-8136-4fcb9f4eaa74)

I am very sure I am doing something wrong but I need someone to throw the solution in my face.

Dont worry it is not an urgent case but I bet you know how it feels if you do not find the issue. 

Best regards,
P0tth34d

**Comment by P0tth34d** [comment]
OK Update after posting this Problem I found out that I did have a blank space in the GCode after Snapshot
Holy moly that is now really embarrassing . I searched for at least one week now.
Sometimes posting screenshots might be needed. Thank you anyways for this great plugin

**Comment by cmuche** [comment]
Hi @P0tth34d !
I'm happy you could fix the problem 😃 And thank you for your input - maybe it would be a good idea to strip spaces when listening to snapshot commands. I think I'll include it in v1.3.0 which will come in a few days (along with some other great new features). If you have any further questions or problems, please don't hesitate to ask 👍
