### ISSUE TITLE
Long names of files cause buttons to go out of frame in list view

### ISSUE THREAD

**Issue by pracovnik** [cmuche/octoprint-timelapseplus#90]
Would you be so kind and make an adjustment to it?

![2023-05-26 09_52_19-Window](https://github.com/cmuche/octoprint-timelapseplus/assets/40662523/ad2671c3-d9d4-41a8-8444-e6aaf8e9e756)

**Comment by cmuche** [comment]
Hi @pracovnik 
Thanks for your input. I'll add it to the backlog 👍

**Comment by cmuche** [comment]
Fixed. Will be released with 1.3.1
