### ISSUE TITLE
The Encoder .... is not supported by your FFmpeg Version

### ISSUE THREAD

**Issue by fly74** [cmuche/octoprint-timelapseplus#93]
@cmuche Hi Chris, the new messages are great, but can you collect them to a list.

I've fixed the first message with recompile ffmpeg, but the message forced me to do another compile.

![Screenshot 2023-05-27 221045](https://github.com/cmuche/octoprint-timelapseplus/assets/38754941/38b75ff5-8308-4caa-a4b6-75fb3b24818d)
![Screenshot 2023-05-27 222914](https://github.com/cmuche/octoprint-timelapseplus/assets/38754941/971a8d89-6104-4ab8-8e2c-9fa95d2d98b5)

**Comment by cmuche** [comment]
Hi @fly74 
That's a good idea. Thanks for your input. I'll add this to the backlog. 👍

**Comment by cmuche** [comment]
Done. Will be released with the next version.
