### ISSUE TITLE
Botton's should be in the next line

### ISSUE THREAD

**Issue by fly74** [cmuche/octoprint-timelapseplus#98]
Hi Chris, on long file names the video buttons are not shown. Maybe they should be on the next line in each case.

![Screenshot 2023-05-31 074707](https://github.com/cmuche/octoprint-timelapseplus/assets/38754941/23c5407f-6fc5-448c-947f-f41327c91b71)

**Comment by cmuche** [comment]
Hi @fly74 
This is a duplicate of https://github.com/cmuche/octoprint-timelapseplus/issues/90 so I'd close this issue. Thank you for your input!
